CREATE TABLE IF NOT EXISTS destination_branches (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(140) NOT NULL,
    code VARCHAR(40) NULL,
    db_host VARCHAR(255) NOT NULL,
    db_port INT UNSIGNED NOT NULL DEFAULT 3306,
    db_database VARCHAR(120) NOT NULL,
    db_username VARCHAR(120) NOT NULL,
    db_password VARCHAR(255) NOT NULL,
    db_charset VARCHAR(40) NOT NULL DEFAULT 'utf8mb4',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    notes VARCHAR(500) NULL,
    last_connection_status VARCHAR(30) NULL,
    last_connection_error VARCHAR(500) NULL,
    last_connection_checked_at DATETIME NULL,
    last_sync_status VARCHAR(30) NULL,
    last_sync_error VARCHAR(500) NULL,
    last_sync_sales INT UNSIGNED NOT NULL DEFAULT 0,
    last_sync_items INT UNSIGNED NOT NULL DEFAULT 0,
    last_sync_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_destination_branches_active (is_active, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
